<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../SplitOS.Contracts/SplitOS.Contracts.csproj" />
    <ProjectReference Include="../SplitOS.Ipc/SplitOS.Ipc.csproj" />
  </ItemGroup>
</Project>
