using System.Text;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace SplitOS.RuntimeHost.Tests;

[TestClass]
public sealed class InstallationIdentityProviderTests
{
    private string _root = null!;

    [TestInitialize]
    public void Initialize()
    {
        _root = Path.Combine(Path.GetTempPath(), "SplitOS-InstallationIdentityTests", Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(_root);
    }

    [TestCleanup]
    public void Cleanup()
    {
        if (Directory.Exists(_root))
        {
            Directory.Delete(_root, recursive: true);
        }
    }

    [TestMethod]
    public async Task ProvisionedIdentityIsReadWithoutMutation()
    {
        var path = Path.Combine(_root, "installation.id");
        await File.WriteAllTextAsync(path, "inst_01HZXQ4RV4M7P2K8D3A9F6C1BN\r\n", new UTF8Encoding(false));
        var before = await File.ReadAllBytesAsync(path);

        var result = await new MachineInstallationIdentityProvider(path).ReadAsync();
        var after = await File.ReadAllBytesAsync(path);

        Assert.IsTrue(result.IsAvailable);
        Assert.AreEqual(InstallationIdentityReadStatus.Available, result.Status);
        Assert.AreEqual("inst_01HZXQ4RV4M7P2K8D3A9F6C1BN", result.InstallationId);
        CollectionAssert.AreEqual(before, after);
    }

    [TestMethod]
    public async Task MissingIdentityIsProvisioningFailureNotAutoGenerated()
    {
        var path = Path.Combine(_root, "missing.id");
        var provider = new MachineInstallationIdentityProvider(path);

        var first = await provider.ReadAsync();
        var second = await provider.ReadAsync();

        Assert.AreEqual(InstallationIdentityReadStatus.Missing, first.Status);
        Assert.AreEqual("INSTALLATION_ID_MISSING", first.ProductCode);
        Assert.AreEqual(InstallationIdentityReadStatus.Missing, second.Status);
        Assert.IsFalse(File.Exists(path));
    }

    [TestMethod]
    public async Task WhitespaceOrControlCharactersAreRejected()
    {
        var path = Path.Combine(_root, "installation.id");
        await File.WriteAllTextAsync(path, "inst valid\n", new UTF8Encoding(false));

        var result = await new MachineInstallationIdentityProvider(path).ReadAsync();

        Assert.AreEqual(InstallationIdentityReadStatus.Invalid, result.Status);
        Assert.AreEqual("INSTALLATION_ID_INVALID", result.ProductCode);
        Assert.IsNull(result.InstallationId);
    }

    [TestMethod]
    public async Task InvalidUtf8IsRejected()
    {
        var path = Path.Combine(_root, "installation.id");
        await File.WriteAllBytesAsync(path, [0x69, 0x6E, 0x73, 0x74, 0x5F, 0xC3, 0x28]);

        var result = await new MachineInstallationIdentityProvider(path).ReadAsync();

        Assert.AreEqual(InstallationIdentityReadStatus.Invalid, result.Status);
    }

    [TestMethod]
    public async Task OversizedIdentityFileIsRejectedBeforeUse()
    {
        var path = Path.Combine(_root, "installation.id");
        await File.WriteAllTextAsync(path, new string('a', 513), new UTF8Encoding(false));

        var result = await new MachineInstallationIdentityProvider(path).ReadAsync();

        Assert.AreEqual(InstallationIdentityReadStatus.Invalid, result.Status);
        Assert.IsNull(result.InstallationId);
    }

    [TestMethod]
    public async Task MoreThanOneTerminalLineIsRejected()
    {
        var path = Path.Combine(_root, "installation.id");
        await File.WriteAllTextAsync(path, "inst_01\nextra\n", new UTF8Encoding(false));

        var result = await new MachineInstallationIdentityProvider(path).ReadAsync();

        Assert.AreEqual(InstallationIdentityReadStatus.Invalid, result.Status);
    }

    [TestMethod]
    public async Task CallerCancellationIsPropagated()
    {
        var path = Path.Combine(_root, "installation.id");
        await File.WriteAllTextAsync(path, "inst_01", new UTF8Encoding(false));
        using var cancellation = new CancellationTokenSource();
        cancellation.Cancel();

        var threw = false;
        try
        {
            await new MachineInstallationIdentityProvider(path).ReadAsync(cancellation.Token);
        }
        catch (OperationCanceledException)
        {
            threw = true;
        }

        Assert.IsTrue(threw, "Expected cancellation to propagate to the caller.");
    }
}
