<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="MSTest.TestAdapter" />
    <PackageReference Include="MSTest.TestFramework" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/SplitOS.RuntimeHost/SplitOS.RuntimeHost.csproj" />
    <ProjectReference Include="../../src/SplitOS.Ipc.Windows/SplitOS.Ipc.Windows.csproj" />
    <ProjectReference Include="../../src/SplitOS.Persistence.Machine/SplitOS.Persistence.Machine.csproj" />
    <ProjectReference Include="../../src/SplitOS.Persistence.User/SplitOS.Persistence.User.csproj" />
    <ProjectReference Include="../../src/SplitOS.Persistence.ProtectedSecrets/SplitOS.Persistence.ProtectedSecrets.csproj" />
  </ItemGroup>
</Project>
